package com.wemall.shriourl.entity;

import java.io.Serializable;

public class ShrioUrl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shiro_url.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shiro_url.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shiro_url.permissions
     *
     * @mbggenerated
     */
    private String def;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shiro_url.roles
     *
     * @mbggenerated
     */
    private String filtername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_shiro_url
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shiro_url.id
     *
     * @return the value of sys_shiro_url.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shiro_url.id
     *
     * @param id the value for sys_shiro_url.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shiro_url.url
     *
     * @return the value of sys_shiro_url.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shiro_url.url
     *
     * @param url the value for sys_shiro_url.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

	public String getDef() {
		return def;
	}

	public void setDef(String def) {
		this.def = def;
	}

	public String getFiltername() {
		return filtername;
	}

	public void setFiltername(String filtername) {
		this.filtername = filtername;
	}




}