package com.wemall.shop.dao;

import java.util.List;

import com.wemall.shop.entity.Shop;

public interface ShopDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pkShop);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    Shop selectByPrimaryKey(String pkShop);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shop record);
    
    List<Shop> selectAllShop(); 
    
    int updateByName(List<String> list);
    
    Shop selecttestwithasoci(String pk_shop);
    
}