package com.wemall.wallet.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class WalletDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_detail.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_detail.amonut
     *
     * @mbggenerated
     */
    private BigDecimal amonut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_detail.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_detail.wid
     *
     * @mbggenerated
     */
    private Wallet wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_detail.id
     *
     * @return the value of wallet_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_detail.id
     *
     * @param id the value for wallet_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_detail.type
     *
     * @return the value of wallet_detail.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_detail.type
     *
     * @param type the value for wallet_detail.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_detail.amonut
     *
     * @return the value of wallet_detail.amonut
     *
     * @mbggenerated
     */
    public BigDecimal getAmonut() {
        return amonut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_detail.amonut
     *
     * @param amonut the value for wallet_detail.amonut
     *
     * @mbggenerated
     */
    public void setAmonut(BigDecimal amonut) {
        this.amonut = amonut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_detail.name
     *
     * @return the value of wallet_detail.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_detail.name
     *
     * @param name the value for wallet_detail.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_detail.wid
     *
     * @return the value of wallet_detail.wid
     *
     * @mbggenerated
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_detail.wid
     *
     * @param wid the value for wallet_detail.wid
     *
     * @mbggenerated
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", amonut=").append(amonut);
        sb.append(", name=").append(name);
        sb.append(", wid=").append(wid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public Wallet getWid() {
		return wid;
	}

	public void setWid(Wallet wid) {
		this.wid = wid;
	}
}