package com.wemall.shop.entity;

import java.io.Serializable;
import java.util.Date;

public class Shop implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.pk_shop
     *
     * @mbggenerated
     */
    private String pkShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.lastedit_time
     *
     * @mbggenerated
     */
    private Date lasteditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    private String promotionInfo;
    
    private String des;
    
    private String imagePath;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.pk_shop
     *
     * @return the value of shop.pk_shop
     *
     * @mbggenerated
     */
    public String getPkShop() {
        return pkShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.pk_shop
     *
     * @param pkShop the value for shop.pk_shop
     *
     * @mbggenerated
     */
    public void setPkShop(String pkShop) {
        this.pkShop = pkShop == null ? null : pkShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.address
     *
     * @return the value of shop.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.address
     *
     * @param address the value for shop.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.phone_number
     *
     * @return the value of shop.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.phone_number
     *
     * @param phoneNumber the value for shop.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.creation_time
     *
     * @return the value of shop.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.creation_time
     *
     * @param creationTime the value for shop.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.lastedit_time
     *
     * @return the value of shop.lastedit_time
     *
     * @mbggenerated
     */
    public Date getLasteditTime() {
        return lasteditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.lastedit_time
     *
     * @param lasteditTime the value for shop.lastedit_time
     *
     * @mbggenerated
     */
    public void setLasteditTime(Date lasteditTime) {
        this.lasteditTime = lasteditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.ts
     *
     * @return the value of shop.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.ts
     *
     * @param ts the value for shop.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

	public String getPromotionInfo() {
		return promotionInfo;
	}

	public void setPromotionInfo(String promotionInfo) {
		this.promotionInfo = promotionInfo;
	}

	public String getDes() {
		return des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}