package com.wemall.wallet.dao;

import com.wemall.wallet.entity.Wallet;

public interface WalletDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated
     */
    Wallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wallet record);
}