package com.wemall.wallet.dao;

import com.wemall.wallet.entity.WalletDetail;

public interface WalletDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    int insert(WalletDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    int insertSelective(WalletDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    WalletDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WalletDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WalletDetail record);
}