package com.wemall.userrole.entity;

import java.io.Serializable;

import com.wemall.role.entity.Role;
import com.wemall.user.entity.User;

public class UserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user
     *
     * @mbggenerated
     */
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role
     *
     * @mbggenerated
     */
    private Role role;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}







}